version: '4.1'
package:
  name: ubuntu-simple-cloud-init
  vendor: eu.5gtango
  version: '0.1'
  maintainer: Ignacio Dominguez (Atos)
  description: Ubuntu simple with 1 VNF and cloud-init
descriptor_extension: yml
files:
- path: ubuntu_1vnf_nsd.yaml
  type: application/vnd.etsi.osm.nsd
  tags:
  - etsi.osm
- path: ubuntu_vnfd.yaml
  type: application/vnd.etsi.osm.vnfd
  tags:
  - file-ref:cloud_init/cloud-config.txt
  - etsi.osm
- path: cloud_init/cloud-config.txt
  type: text/x-shellscript
  tags:
  - etsi.osm
