---
descriptor_extension: yml
version: '0.5'
package:
  vendor: "eu.5gtango"
  name: "media-performance-test-single-ns-multiple-td"
  version: "0.1"
  maintainer: "Felipe Vicens, ATOS"
  description: "This is a 5GTANGO test package for media perfomance Benchmarking"
files:
  - path: "Definitions/test-descriptor.yml"
    type: "application/vnd.5gtango.tstd"
    testing_tags:
      - "ns-tt-matches-multiple-td-tt"
  - path: "Icons/upb_logo.png"
    type: "image/png"
  - path: "Licenses/LICENSE"
    type: "text/plain"
