descriptor_extension: yml
version: '0.5'
files:
- path: Definitions/nsd/nsd_smpilot_ns1.yml
  type: application/vnd.5gtango.nsd
  tags:
  - eu.5gtango
  testing_tags:
  - industrial-pilot-broker-egm
  - industrial-pilot-NS1-functional
  - IPreq008
  - IPreq008-crash
  - IPreq008-payload
  - IPreq013-lowdr
  - IPreq09
  - IPreq09-rampup
- path: Definitions/vnfd/vnfd_cc.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: Definitions/vnfd/vnfd_eae.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
package:
  name: tng-smpilot-ns1-k8s-egm
  version: '1.9'
  maintainer: Manuel Peuster (Paderborn University)
  vendor: eu.5gtango
  description: 'Smart manufacturing pilot: Factory edge service (NS1) for vim-emu.'
uuid: 44f97451-0c69-4624-aeeb-cf14fcc8102e
