---
descriptor_extension: yml
version: '0.5'
package:
  vendor: "eu.5gtango"
  name: "generic-probes-test"
  version: "0.1"
  maintainer: "Felipe Vicens (ATOS)"
  description: "This is a 5GTANGO test package for test probes"
files:
  - path: "Definitions/test-descriptor.yml"
    type: "application/vnd.5gtango.tstd"
    testing_tags:
      - "generic-probes"
  - path: "Licenses/LICENSE"
    type: "text/plain"
